spring:
  datasource:
    url: jdbc:mysql://localhost:3306?managment_system
    username: root
    password: EMBETEMariam131621!
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    database: mysql
    show-sql: true
    properties:
          javax:
            persistence:
              schema-generation:
                create-source: metadata
                scripts:
                  action: create
                  create-target: ms_database_create.sql
