CREATE DATABASE IF NOT EXISTS managment_system

INSERT IGNORE INTO product (product_id, product_name)
VALUES ('1','BEAR_BANNER'),
        ('2','ARC_STAND_BANNER'),
        ('3','PHOTO_FRAME_STANDING_BANNER'),
        ('4','RING_BANNER'),
        ('5','DANGLER_BANNER'),
        ('6','POWER_BRANDING_BANNER'),
        ('7','WALL_BANNER'),
        ('8','VENUE_BANNER'),
        ('9','VENDOR_BANNER'),
        ('10','TENT_BACK_SELF_STANDING_BANNER'),
        ('11','TEARDROP_BANNER'),
        ('12','SELF_STANDING_BANNER'),
        ('13','ROLL_UP_BANNER'),
        ('14','PITCH_SIDE_BRANDING_BANNER'),
        ('15','NEW_YEAR_BANNER'),
        ('16','LIGHT_BOX_BANNER'),
        ('17','FASTING_ACTIVATION_BANNER'),
        ('18','DROP_DOWN_BANNER'),
        ('19','DANCE_FLOOR_BANNER'),
        ('20','CONCRETE_BASE_SELF_FLYING_BANNER'),
        ('21','CONCRETE_BASE_BAR_BRANDING_BANNER'),
        ('22','COLUMN_BRANDING_BANNER'),
        ('23','BARRICADE_SELF_STAND_BANNER'),
        ('24','BACK_DROP_BANNER'),
        ('25','PRICE_COMMUNICATION_STICKER'),
        ('26','T-SHIRT_STICKER'),
        ('27','DANGLER_STICKER'),
        ('28','INFORMATION_CIRCLE_SIGN_STICKER'),
        ('29','FRIDGE_STICKER'),
        ('30','MESH_STICKER'),
        ('31','CAR_BRANDING_STICKER');


        INSERT IGNORE INTO material (material_id, material_Name)
                 VALUES ('1','BANNER'),
                        ('2','STICKER'),
                        ('3','ROLL-UP'),
                        ('4','INK BLUE'),
        				('5','INK BLACK'),
        				('6','INK YELLOW'),
        				('7','INK RED'),
        				('8','GLUE'),
        				('9','LED POWER SUPPLY'),
        				('10','CIRCULAR LED LIGHT'),
        				('11','LED WIRE'),
        				('12','MICA TRANSPORT'),
        				('13','SHEET METAL'),
        				('14','SOLVENT'),
        			    ('15','RING'),
        				('16','ADHESIVE/MASTISH'),
        				('17','BRUSH'),
        				('18','CONCRETE NAIL'),
        				('19','ELECTRODE'),
        				('20','HING'),
        				('21','HOLLOW SECTION RHS'),
        		        ('22','PLUG'),
        				('23','WELDING CLAMP'),
        				('24','CABLE'),
        				('25','CHAIN'),
        				('26','LED FLOURECENT'),
        				('27','GRINDER DISC SMALL'),
        				('28','CUTTING DISC BIG'),
                        ('29','BLACK PAINT'),
                        ('30','CUTTING KNIFE'),
                        ('31','GINDING DISC SAND'),
                        ('32','CUTTER SMALL'),
        				('33','WELDING WIRE'),
        				('34','LED TS 90'),
        				('35','FISHER');